[theme]
# Primary accent color for interactive elements.
primaryColor = "#6B5B95"

# Background color for the main content area.
backgroundColor = "#1A1A1A"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#2B2B2B"

# Color used for almost all text.
textColor = "#FFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"